In [1]:
from Linear_Regression import LinearRegressiongradient

In [2]:
import numpy as np

In [3]:
from sklearn import datasets

In [4]:
import pandas as pd

In [5]:
cc=datasets.make_regression(n_samples=100, n_features=10)

In [6]:
cc[0].shape[0]

100

In [7]:
idenxs=np.random.choice(len(cc[0]),75,replace=False)

In [8]:
idenxs

array([15, 19, 11, 90, 99, 81, 57, 24, 49, 53, 76, 73, 72, 36, 32, 89, 31,
        5, 74, 97, 79, 40, 25, 18, 17, 37,  3, 92, 23, 96, 77, 66, 75, 69,
       87, 26, 56,  8,  2, 30, 13, 21, 60, 83,  7, 51, 84, 47, 68, 71, 33,
       93, 64, 86, 50, 35,  9, 94, 34, 20, 10,  1, 14, 65, 67, 85, 62, 16,
       88, 98, 12, 58,  6, 52, 38])

In [9]:
train=np.zeros([75,10])

In [10]:
train.shape

(75, 10)

In [11]:
test=np.zeros([25,10])

In [12]:
labels_train=np.zeros([75,1])

In [13]:
labels_test=np.zeros([25,1])

In [14]:
train

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 

In [15]:
j=0
k=0
for i in range(100):
    if i in idenxs:
        train[j]=cc[0][i]
        labels_train[j]=cc[1][i]
        j+=1
    else :
        test[k]=cc[0][i]
        labels_test[k]=cc[1][i]
        k+=1
        
        

In [16]:
test[24]

array([ 1.05883515, -0.66257526,  0.40440249,  1.2093692 ,  1.07032923,
       -3.05299218, -1.52134115,  0.8025166 , -1.53755198,  1.21427947])

In [17]:
cc[0][45]

array([-1.06293958,  0.36296555,  0.63290794, -0.21889512, -2.00165332,
        0.39069605, -0.30098325, -0.34732585, -0.12104216,  0.97211533])

In [18]:
traindf = pd.DataFrame(train, columns = ['A','B','C','D','E','F','G','H','I','K'])

In [19]:
testdf = pd.DataFrame(test, columns = ['A','B','C','D','E','F','G','H','I','K'])

In [20]:
labels_traindf = pd.DataFrame(labels_train, columns = ['Column_A'])

In [21]:
labels_testdf = pd.DataFrame(labels_test, columns = ['Column_A'])

In [28]:
a=LinearRegressiongradient(0.01,2,100)

In [29]:
a.learn(traindf,labels_traindf)

batch size:  37
w0  [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
epoch number 1 :

error        Column_A
0    63.138960
1   -30.805034
2   -82.754809
3   -29.406220
4   -29.790212
..         ...
70  -82.778439
71   37.030617
72  204.953978
73  -22.302527
74  -96.935963

[75 rows x 1 columns]
mse :  Column_A    20240.564504
dtype: float64
epoch number 2 :

error        Column_A
0    54.030600
1   -26.433781
2   -73.026339
3   -25.356696
4   -29.240906
..         ...
70  -67.565492
71   31.060189
72  179.597739
73  -12.827590
74  -83.381909

[75 rows x 1 columns]
mse :  Column_A    14740.397561
dtype: float64
epoch number 3 :

error        Column_A
0    46.023176
1   -22.705271
2   -64.531523
3   -22.060124
4   -28.434133
..         ...
70  -54.919283
71   26.064350
72  157.259595
73   -5.814743
74  -71.807610

[75 rows x 1 columns]
mse :  Column_A    10769.438777
dtype: float64
epoch number 4 :

error        Column_A
0    39.015806
1   -19.521985
2   -57.103434
3  

[75 rows x 1 columns]
mse :  Column_A    0.03218
dtype: float64
epoch number 61 :

error      Column_A
0  -0.233506
1  -0.029506
2  -0.184614
3  -0.119342
4  -0.379314
..       ...
70  0.156613
71 -0.004190
72  0.071003
73  0.013500
74 -0.164468

[75 rows x 1 columns]
mse :  Column_A    0.02709
dtype: float64
epoch number 62 :

error      Column_A
0  -0.216550
1  -0.027158
2  -0.168562
3  -0.110078
4  -0.349215
..       ...
70  0.143937
71 -0.004415
72  0.063000
73  0.011509
74 -0.150862

[75 rows x 1 columns]
mse :  Column_A    0.022812
dtype: float64
epoch number 63 :

error      Column_A
0  -0.200759
1  -0.025006
2  -0.153929
3  -0.101553
4  -0.321490
..       ...
70  0.132270
71 -0.004575
72  0.055943
73  0.009804
74 -0.138390

[75 rows x 1 columns]
mse :  Column_A    0.019216
dtype: float64
epoch number 64 :

error      Column_A
0  -0.186061
1  -0.023030
2  -0.140589
3  -0.093706
4  -0.295954
..       ...
70  0.121535
71 -0.004681
72  0.049716
73  0.008344
74 -0.126955

[75 rows x

In [24]:
print(labels_testdf)
print(type(labels_testdf))

      Column_A
0    43.408136
1     9.717640
2   149.362986
3    -7.039899
4   132.070757
5  -388.903434
6   122.532945
7  -141.156617
8   134.600159
9  -152.040688
10   61.206054
11  -98.576644
12 -121.038912
13  -95.548623
14  138.278046
15 -261.124825
16   49.508387
17 -234.931949
18   52.836229
19  139.887792
20  108.980243
21  -97.375275
22   73.136325
23   77.875725
24   29.865741
<class 'pandas.core.frame.DataFrame'>


In [30]:
b=a.infer(testdf)

In [31]:
c=b.to_numpy()

In [32]:
 for i in range(25):
        print("{},{}".format(labels_test[i],c[i]))

[43.40813604],[43.40913341]
[9.7176399],[9.73487561]
[149.36298561],[149.35747463]
[-7.03989937],[-7.04387211]
[132.07075726],[132.06413437]
[-388.90343425],[-388.90496324]
[122.53294547],[122.52268598]
[-141.15661727],[-141.15970705]
[134.60015881],[134.58010229]
[-152.04068808],[-152.03061895]
[61.2060542],[61.20481099]
[-98.57664382],[-98.57452077]
[-121.03891169],[-121.03676798]
[-95.5486231],[-95.54828652]
[138.27804565],[138.28167912]
[-261.12482533],[-261.14360519]
[49.50838691],[49.5045046]
[-234.93194858],[-234.91773857]
[52.83622872],[52.84245581]
[139.88779204],[139.89935649]
[108.98024278],[108.96896472]
[-97.37527483],[-97.37629339]
[73.13632491],[73.14247961]
[77.87572473],[77.87487075]
[29.86574061],[29.87060587]
