In [ ]:
#This first part is for the simple SVM(whithout gradient descent)

In [43]:
import numpy as np
from SVM1 import SVM
import pandas as pd

In [44]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00229/Skin_NonSkin.txt" 
data = pd.read_csv(url, header = None, sep='\t')

np.random.seed(1)

msk = np.random.rand(len(data)) < 0.8
data[msk].to_csv('train.csv', header=False, index=False)
data[~msk].to_csv('test.csv', header=False, index=False)

In [3]:
data.head()

0   1    2  3
0  74  85  123  1
1  73  84  122  1
2  72  83  121  1
3  70  81  119  1
4  70  81  119  1

In [4]:
loss_list = []
acc_list = []
tp_list = []
tn_list = []
w_list = []

for i in range(100):
    
    #print '\nSeed',i
    
    np.random.seed(i)
    
    svm = SVM(1,3)

    l,acc,tp,tn,w = svm.fit()

    loss_list.append(l)
    acc_list.append(acc)
    tp_list.append(tp)
    tn_list.append(tn)
    w_list.append(w)

print('Loss', sum(loss_list)/len(loss_list))
print('Accuracy', sum(acc_list)/len(acc_list) * 100, '%')
print('True Positives', sum(tp_list)/len(tp_list) * 100, '%')
print('True Negatives',sum(tn_list)/len(tn_list) * 100, '%')

Loss 0.3411656270013287
Accuracy 93.00312704381949 %
True Positives 99.37931034482757 %
True Negatives 91.33418433132191 %


In [ ]:
#This second part is for the  SVM whith batch gradient descent

In [45]:
import numpy as np 
from SVM1_BGD import SVM

In [46]:
def data(test=False):
        if test:
            with open('test.csv','r') as f:
                samples = f.readlines()

                for t,row in enumerate(samples):

                    row = row.replace('\n','')
                    row = row.split(',')

                    target = -1.

                    if row[3] == '1':
                        target = 1.
                    del row[3]

                    x = [float(c) for c in row] #inputs + bias

                    yield t, x,target

        else:

            with open('train.csv','r') as f:
                samples = f.readlines()
                random.shuffle(samples)

                for t,row in enumerate(samples):

                    row = row.replace('\n','')
                    row = row.split(',')

                    target = -1.

                    if row[3] == '1':
                        target = 1.
                    del row[3]

                    x = [float(c) for c in row] #inputs + bias

                    yield t, x,target

In [47]:
features = []
for t,x,c in data(True):
    x.append(c)
    features.append(x)


In [48]:
data = np.array(features)

In [49]:
data

array([[ 78.,  89., 127.,   1.],
       [ 80.,  88., 128.,   1.],
       [ 83.,  91., 131.,   1.],
       ...,
       [163., 162., 112.,  -1.],
       [163., 162., 112.,  -1.],
       [163., 162., 112.,  -1.]])

In [36]:
def hinge_loss(target,y):
    return max(0,1 - target*y)

In [37]:
def sign(x):
    if x<=0:
        return -1.
    else:
        return 1.

In [50]:
q = SVM()

In [ ]:
q.learn(data)

In [33]:
dd = data[2][:-1]
y=data[2][-1]

In [34]:
dd

array([162., 181., 232.])

In [35]:
q.infer(dd)

array([-11.89159354])

In [38]:
print(hinge_loss(y,q.infer(dd)))

[12.89159354]


In [39]:
s=[]
for i in data:
    dd = i[:-1]
    y=i[-1]
    pred= q.infer(dd)
    hl=hinge_loss(y,pred)
    pred=sign(pred)
    s.append((y,pred,hl))

In [40]:
j=0
for i in range(len(s)):
    if s[i][1]!=s[i][0]:
        j+=1
        print(s[i])
print("\n hello : ",j)
    

(-1.0, 1.0, array([173.76271858]))
(1.0, -1.0, array([12.89159354]))
(1.0, -1.0, array([5.40263269]))
(1.0, -1.0, array([20.6573333]))
(1.0, -1.0, array([32.6659967]))
(-1.0, 1.0, array([106.47198213]))
(1.0, -1.0, array([32.19649744]))
(1.0, -1.0, array([8.35587342]))
(1.0, -1.0, array([53.31165995]))
(1.0, -1.0, array([4.50552414]))
(-1.0, 1.0, array([144.11836679]))
(1.0, -1.0, array([31.09435494]))
(-1.0, 1.0, array([218.60491377]))
(1.0, -1.0, array([6.96581611]))
(-1.0, 1.0, array([158.10040113]))
(-1.0, 1.0, array([122.11825806]))
(1.0, -1.0, array([36.98079263]))
(1.0, -1.0, array([29.44861285]))
(-1.0, 1.0, array([148.39822694]))
(-1.0, 1.0, array([21.05053523]))
(-1.0, 1.0, array([184.2389013]))
(1.0, -1.0, array([15.34550395]))
(-1.0, 1.0, array([81.52153673]))
(1.0, -1.0, array([2.75064677]))
(-1.0, 1.0, array([42.32608465]))
(-1.0, 1.0, array([21.45739998]))
(1.0, -1.0, array([34.95166267]))
(-1.0, 1.0, array([285.5952397]))
(-1.0, 1.0, array([47.84692629]))
(1.0, -1.0, ar

(1.0, -1.0, array([38.03543533]))
(1.0, -1.0, array([27.58044669]))
(1.0, -1.0, array([33.93057895]))
(-1.0, 1.0, array([32.51659808]))
(1.0, -1.0, array([19.71077553]))
(1.0, -1.0, array([38.54397606]))
(-1.0, 1.0, array([483.37444208]))
(1.0, -1.0, array([6.84597055]))
(1.0, -1.0, array([28.94823218]))
(1.0, -1.0, array([29.90384909]))
(1.0, -1.0, array([39.40322083]))
(1.0, -1.0, array([32.20555658]))
(1.0, -1.0, array([20.95978974]))
(1.0, -1.0, array([38.97886599]))
(-1.0, 1.0, array([104.09159862]))
(-1.0, 1.0, array([23.01049785]))
(-1.0, 1.0, array([43.60633065]))
(1.0, -1.0, array([11.32247809]))
(-1.0, 1.0, array([18.57275317]))
(1.0, -1.0, array([57.67693153]))
(1.0, -1.0, array([27.24503208]))
(1.0, -1.0, array([42.22980882]))
(-1.0, 1.0, array([483.37444208]))
(-1.0, 1.0, array([190.87399991]))
(1.0, -1.0, array([39.81643976]))
(1.0, -1.0, array([8.11370384]))
(1.0, -1.0, array([31.64386264]))
(-1.0, 1.0, array([152.30638462]))
(1.0, -1.0, array([34.00928235]))
(1.0, -1.0,

(1.0, -1.0, array([1.37482856]))
(1.0, -1.0, array([63.03731102]))
(-1.0, 1.0, array([366.95572518]))
(-1.0, 1.0, array([37.82064859]))
(-1.0, 1.0, array([384.50122042]))
(1.0, -1.0, array([31.87594665]))
(1.0, -1.0, array([23.24605652]))
(1.0, -1.0, array([29.23509664]))
(1.0, -1.0, array([20.8831631]))
(-1.0, 1.0, array([344.043668]))
(-1.0, 1.0, array([236.57148546]))
(1.0, -1.0, array([40.15125356]))
(1.0, -1.0, array([39.58955962]))
(-1.0, 1.0, array([130.51648979]))
(-1.0, 1.0, array([160.46509697]))
(1.0, -1.0, array([13.08328748]))
(-1.0, 1.0, array([46.33411935]))
(-1.0, 1.0, array([160.05353265]))
(-1.0, 1.0, array([40.5145492]))
(1.0, -1.0, array([26.71096509]))
(1.0, -1.0, array([70.49806804]))
(1.0, -1.0, array([29.25113816]))
(1.0, -1.0, array([55.5919947]))
(1.0, -1.0, array([31.42501521]))
(-1.0, 1.0, array([224.33386516]))
(-1.0, 1.0, array([34.41256984]))
(1.0, -1.0, array([30.01668836]))
(1.0, -1.0, array([58.06772738]))
(1.0, -1.0, array([40.59803147]))
(1.0, -1.0, 

(1.0, -1.0, array([39.95585563]))
(1.0, -1.0, array([27.4925568]))
(1.0, -1.0, array([6.77041818]))
(1.0, -1.0, array([14.16510759]))
(1.0, -1.0, array([8.89529555]))
(-1.0, 1.0, array([33.30262112]))
(1.0, -1.0, array([35.74604144]))
(1.0, -1.0, array([22.07366895]))
(1.0, -1.0, array([57.70143137]))
(-1.0, 1.0, array([296.7053699]))
(-1.0, 1.0, array([158.13043477]))
(-1.0, 1.0, array([164.48219081]))
(-1.0, 1.0, array([107.83976763]))
(-1.0, 1.0, array([197.05570909]))
(-1.0, 1.0, array([98.74665983]))
(1.0, -1.0, array([32.23005642]))
(-1.0, 1.0, array([258.16846082]))
(1.0, -1.0, array([35.81373628]))
(1.0, -1.0, array([38.64405219]))
(-1.0, 1.0, array([181.70261088]))
(-1.0, 1.0, array([153.97870332]))
(1.0, -1.0, array([28.00212395]))
(1.0, -1.0, array([29.53442597]))
(1.0, -1.0, array([48.70837233]))
(-1.0, 1.0, array([108.64398499]))
(1.0, -1.0, array([30.66049143]))
(-1.0, 1.0, array([56.67937538]))
(-1.0, 1.0, array([148.4383153]))
(-1.0, 1.0, array([146.55520927]))
(1.0, -1

(1.0, -1.0, array([53.68433753]))
(1.0, -1.0, array([32.46048929]))
(-1.0, 1.0, array([98.55126191]))
(1.0, -1.0, array([59.9998844]))
(-1.0, 1.0, array([1.16847277]))
(-1.0, 1.0, array([141.57919276]))
(-1.0, 1.0, array([155.93268261]))
(1.0, -1.0, array([26.26804244]))
(-1.0, 1.0, array([244.81280777]))
(-1.0, 1.0, array([94.94750743]))
(1.0, -1.0, array([4.59221241]))
(-1.0, 1.0, array([107.05817591]))
(-1.0, 1.0, array([124.56783629]))
(1.0, -1.0, array([39.56505978]))
(1.0, -1.0, array([34.87566077]))
(1.0, -1.0, array([20.56096116]))
(-1.0, 1.0, array([129.91217773]))
(1.0, -1.0, array([32.85293629]))
(1.0, -1.0, array([29.25113816]))
(-1.0, 1.0, array([104.48239448]))
(1.0, -1.0, array([28.3620384]))
(-1.0, 1.0, array([42.5948343]))
(1.0, -1.0, array([11.51787602]))
(-1.0, 1.0, array([184.62969716]))
(-1.0, 1.0, array([166.16462245]))
(1.0, -1.0, array([34.0337822]))
(1.0, -1.0, array([5.45846347]))
(1.0, -1.0, array([20.49236724]))
(1.0, -1.0, array([24.57390147]))
(1.0, -1.0, 

In [41]:
acc=(len(s)-j)/len(s)*100

In [42]:
acc

89.25359712230215